language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - pip3 install python-coveralls
  - pip3 install coverage
  - pip3 install pandas
  - pip3 install scipy
  - pip3 install datawig
  - pip3 install gensim
  - pip3 install pattern
  - pip3 install iso-639
  - pip3 install langdetect
  - pip3 install textstat
  - pip3 install spellchecker
  - pip3 install nltk
script:
  - python3 -m unittest discover
  - coverage run --source shift_detector -m unittest discover
after_success:
  - coveralls
