language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip3 install python-coveralls
  - pip3 install coverage
  - pip3 install nose
  - pip3 install pandas
  - pip3 install scipy
  - pip3 install datawig
  - pip3 install gensim
  - pip3 install google-compute-engine
script:
  - python3 -m unittest discover
  - nosetests --with-coverage --cover-package=shift_detector
after_success:
  - coveralls
