language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - pip3 install python-coveralls
  - pip3 install coverage
  - pip3 install -r requirements.txt
script:
  - python3 nltk_stopwords_download.py
  - coverage run --source shift_detector -m unittest discover
after_success:
  - coveralls
