User's Guide
------------

This part of the documentation, which is mostly prose, focuses on
step-by-step instructions for shift detection with Morpheus.

.. toctree::
   :maxdepth: 2

   installation
   quickstart
   tutorial/index
   checks/index

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

Additional Notes
----------------

.. toctree::
   :maxdepth: 2

   glossary
