#!/bin/sh

# Set these paths appropriately

BIN="/Users/lkkll/shift-detector/treetagger/bin"
CMD="/Users/lkkll/shift-detector/treetagger/cmd"
LIB="/Users/lkkll/shift-detector/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
