#!/bin/sh

# Set these paths appropriately

BIN="/Users/lkkll/shift-detector/treetagger/bin"
CMD="/Users/lkkll/shift-detector/treetagger/cmd"
LIB="/Users/lkkll/shift-detector/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
