#!/bin/sh

# Set these paths appropriately

BIN="/Users/lkkll/shift-detector/treetagger/bin"
CMD="/Users/lkkll/shift-detector/treetagger/cmd"
LIB="/Users/lkkll/shift-detector/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/middle-high-german-abbreviations
PARFILE=${LIB}/middle-high-german.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
