#!/bin/sh

# Set these paths appropriately

BIN="/Users/lkkll/shift-detector/treetagger/bin"
CMD="/Users/lkkll/shift-detector/treetagger/cmd"
LIB="/Users/lkkll/shift-detector/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
